import { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { doc, getDoc, collection, getDocs } from 'firebase/firestore';
import { db } from '../firebase/config';
import { gradeColor } from '../utils/grading';
import Layout from '../components/Layout';

export default function Merit() {
  const { projectId } = useParams();
  const navigate = useNavigate();
  const [project,  setProject]  = useState(null);
  const [students, setStudents] = useState([]);
  const [loading,  setLoading]  = useState(true);
  const [sortBy,   setSortBy]   = useState('gpa'); // 'gpa' | 'roll'
  const [filter,   setFilter]   = useState('all'); // 'all' | 'pass' | 'fail'
  const [generating, setGenerating] = useState(false);

  useEffect(() => { fetchAll(); }, [projectId]);

  async function fetchAll() {
    try {
      const proj = await getDoc(doc(db, 'projects', projectId));
      if (!proj.exists()) { navigate('/'); return; }
      setProject({ id: proj.id, ...proj.data() });
      const snap = await getDocs(collection(db, 'projects', projectId, 'students'));
      setStudents(snap.docs.map(d => ({ id: d.id, ...d.data() })));
    } catch {}
    setLoading(false);
  }

  function getRanked() {
    let list = [...students];
    if (filter === 'pass') list = list.filter(s => s.passed);
    if (filter === 'fail') list = list.filter(s => !s.passed);

    if (sortBy === 'gpa') {
      list.sort((a, b) => {
        if (b.overallGpa !== a.overallGpa) return b.overallGpa - a.overallGpa;
        return a.rollNo - b.rollNo;
      });
    } else {
      list.sort((a, b) => a.rollNo - b.rollNo);
    }
    return list;
  }

  async function downloadPDF() {
    setGenerating(true);
    try {
      const { default: jsPDF } = await import('jspdf');
      const { default: autoTable } = await import('jspdf-autotable');

      const pdf    = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
      const ranked = getRanked();
      const subjs  = project.subjects || [];

      // Header
      pdf.setFontSize(18);
      pdf.setFont('helvetica', 'bold');
      pdf.text('MERIT LIST', 105, 18, { align: 'center' });
      pdf.setFontSize(12);
      pdf.setFont('helvetica', 'normal');
      pdf.text(project.schoolName || '', 105, 26, { align: 'center' });
      pdf.setFontSize(10);
      pdf.text(`${project.className} | ${project.examName} | ${project.year || ''}`, 105, 32, { align: 'center' });
      pdf.text(`Total Students: ${students.length}  |  Passed: ${students.filter(s=>s.passed).length}  |  Failed: ${students.filter(s=>!s.passed).length}`, 105, 38, { align: 'center' });

      // Line
      pdf.setDrawColor(200, 200, 200);
      pdf.line(14, 41, 196, 41);

      // Build columns: Rank, Name, Roll, [subjects...], GPA, Grade, Result
      const subjectCols = subjs.map(s => ({ header: s.name.length > 8 ? s.name.slice(0, 8) + '.' : s.name, dataKey: s.name }));
      const columns = [
        { header: '#',      dataKey: 'rank'   },
        { header: 'Name',   dataKey: 'name'   },
        { header: 'Roll',   dataKey: 'roll'   },
        ...subjectCols,
        { header: 'GPA',    dataKey: 'gpa'    },
        { header: 'Grade',  dataKey: 'grade'  },
        { header: 'Result', dataKey: 'result' },
      ];

      const rows = ranked.map((s, idx) => {
        const row = {
          rank:   idx + 1,
          name:   s.name,
          roll:   s.rollNo,
          gpa:    s.overallGpa?.toFixed(2),
          grade:  s.overallGrade,
          result: s.passed ? 'PASS' : 'FAIL',
        };
        subjs.forEach((subj, i) => {
          const r = s.subjectResults?.[i];
          row[subj.name] = r ? `${r.total.toFixed(0)}` : '-';
        });
        return row;
      });

      autoTable(pdf, {
        startY: 45,
        columns,
        body: rows,
        styles: { fontSize: 8, cellPadding: 2.5, halign: 'center' },
        headStyles: { fillColor: [15, 118, 110], textColor: 255, fontStyle: 'bold' },
        columnStyles: { name: { halign: 'left' } },
        didDrawCell: (data) => {
          if (data.column.dataKey === 'result' && data.section === 'body') {
            const val = data.cell.raw;
            if (val === 'PASS') pdf.setTextColor(34, 197, 94);
            else pdf.setTextColor(239, 68, 68);
          }
        },
        alternateRowStyles: { fillColor: [245, 245, 245] },
        margin: { left: 14, right: 14 },
      });

      // Footer
      const pageCount = pdf.internal.getNumberOfPages();
      for (let i = 1; i <= pageCount; i++) {
        pdf.setPage(i);
        pdf.setFontSize(8);
        pdf.setTextColor(150);
        pdf.text(`Generated by EduGrade · Page ${i} of ${pageCount}`, 105, 290, { align: 'center' });
      }

      pdf.save(`${project.examName}_merit_list.pdf`);
    } catch (err) { alert('PDF generation failed: ' + err.message); }
    setGenerating(false);
  }

  if (loading) return <Layout projectId={projectId}><div className="text-center text-gray-500 py-20">Loading…</div></Layout>;
  if (!project) return null;

  const ranked  = getRanked();
  const top3    = [...students].sort((a, b) => b.overallGpa - a.overallGpa || a.rollNo - b.rollNo).slice(0, 3);
  const subjects = project.subjects || [];

  const medalColors = ['text-yellow-400', 'text-gray-300', 'text-orange-400'];
  const medalEmoji  = ['🥇', '🥈', '🥉'];

  return (
    <Layout projectId={projectId}>
      <div className="mb-5">
        <button onClick={() => navigate('/')} className="text-gray-500 hover:text-white text-sm mb-2 transition-colors">← Home</button>
        <p className="text-xs text-cyan-400 font-semibold uppercase tracking-wider mb-0.5">Rankings</p>
        <h1 className="text-xl font-bold">Merit Table</h1>
        <p className="text-gray-500 text-sm">{project.examName} · {project.className}</p>
      </div>

      {/* Top Performers */}
      {top3.length > 0 && (
        <div className="mb-5">
          <p className="text-xs text-yellow-400 font-semibold uppercase tracking-wider mb-3">🏆 Top Performers</p>
          <div className={`grid gap-3 ${top3.length === 1 ? 'grid-cols-1' : top3.length === 2 ? 'grid-cols-2' : 'grid-cols-3'}`}>
            {top3.map((s, i) => (
              <div key={s.id} className={`bg-gray-900 rounded-2xl p-4 border text-center ${i === 0 ? 'border-yellow-500/50 bg-yellow-950/20' : 'border-gray-800'}`}>
                <div className="text-2xl mb-1">{medalEmoji[i]}</div>
                <p className="font-bold text-sm truncate">{s.name}</p>
                <p className="text-gray-500 text-xs mb-2">Roll {s.rollNo}</p>
                <div className={`text-lg font-black ${medalColors[i]}`}>{s.overallGpa?.toFixed(2)}</div>
                <div className={`text-xs font-semibold mt-0.5 ${gradeColor(s.overallGrade)}`}>{s.overallGrade}</div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Controls */}
      <div className="flex gap-2 mb-4 flex-wrap">
        <div className="flex gap-1 bg-gray-900 rounded-xl p-1 border border-gray-800">
          {[['gpa', 'By GPA'], ['roll', 'By Roll']].map(([v, l]) => (
            <button key={v} onClick={() => setSortBy(v)}
              className={`px-3 py-1.5 rounded-lg text-xs font-semibold transition-all ${sortBy === v ? 'bg-cyan-500 text-white' : 'text-gray-400 hover:text-white'}`}>
              {l}
            </button>
          ))}
        </div>
        <div className="flex gap-1 bg-gray-900 rounded-xl p-1 border border-gray-800">
          {[['all', 'All'], ['pass', '✓ Pass'], ['fail', '✕ Fail']].map(([v, l]) => (
            <button key={v} onClick={() => setFilter(v)}
              className={`px-3 py-1.5 rounded-lg text-xs font-semibold transition-all ${filter === v ? 'bg-cyan-500 text-white' : 'text-gray-400 hover:text-white'}`}>
              {l}
            </button>
          ))}
        </div>
      </div>

      {/* Table */}
      <div className="bg-gray-900 rounded-2xl border border-gray-800 overflow-hidden mb-5">
        <div className="overflow-x-auto no-scrollbar">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-gray-800">
                <th className="text-left px-4 py-3 text-xs font-semibold text-gray-400 whitespace-nowrap">#</th>
                <th className="text-left px-4 py-3 text-xs font-semibold text-gray-400 whitespace-nowrap">NAME</th>
                <th className="text-center px-3 py-3 text-xs font-semibold text-gray-400 whitespace-nowrap">ROLL</th>
                {subjects.map((s, i) => (
                  <th key={i} className="text-center px-3 py-3 text-xs font-semibold text-gray-400 whitespace-nowrap">
                    {s.name.length > 6 ? s.name.slice(0, 6) + '.' : s.name}
                  </th>
                ))}
                <th className="text-center px-3 py-3 text-xs font-semibold text-gray-400 whitespace-nowrap">GPA</th>
                <th className="text-center px-3 py-3 text-xs font-semibold text-gray-400 whitespace-nowrap">GRADE</th>
                <th className="text-center px-3 py-3 text-xs font-semibold text-gray-400 whitespace-nowrap">RESULT</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-800">
              {ranked.length === 0 ? (
                <tr><td colSpan={6 + subjects.length} className="text-center py-10 text-gray-500 text-sm">No students</td></tr>
              ) : ranked.map((s, idx) => (
                <tr key={s.id} className={`hover:bg-gray-800/50 transition-colors ${idx < 3 && sortBy === 'gpa' && filter === 'all' ? 'bg-yellow-950/10' : ''}`}>
                  <td className="px-4 py-3 text-gray-400 text-xs">
                    {sortBy === 'gpa' && filter === 'all' && idx < 3
                      ? <span className="text-base">{medalEmoji[idx]}</span>
                      : idx + 1}
                  </td>
                  <td className="px-4 py-3 font-semibold text-gray-100 whitespace-nowrap">{s.name}</td>
                  <td className="px-3 py-3 text-center text-gray-400">{s.rollNo}</td>
                  {subjects.map((_, i) => {
                    const r = s.subjectResults?.[i];
                    return (
                      <td key={i} className="px-3 py-3 text-center">
                        <span className={`text-xs font-semibold ${r?.passed ? 'text-gray-300' : 'text-red-400'}`}>
                          {r ? r.total.toFixed(0) : '-'}
                        </span>
                      </td>
                    );
                  })}
                  <td className="px-3 py-3 text-center font-bold text-cyan-400">{s.overallGpa?.toFixed(2)}</td>
                  <td className={`px-3 py-3 text-center font-bold ${gradeColor(s.overallGrade)}`}>{s.overallGrade}</td>
                  <td className="px-3 py-3 text-center">
                    <span className={`text-xs font-bold px-2 py-0.5 rounded-lg ${s.passed ? 'bg-green-950 text-green-400' : 'bg-red-950 text-red-400'}`}>
                      {s.passed ? 'PASS' : 'FAIL'}
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Download PDF */}
      <button onClick={downloadPDF} disabled={generating || students.length === 0}
        className="w-full bg-gradient-to-r from-cyan-500 to-blue-500 hover:from-cyan-400 hover:to-blue-400 text-white font-bold py-4 rounded-2xl transition-all disabled:opacity-50 shadow-lg shadow-cyan-900/30 flex items-center justify-center gap-2">
        {generating ? (
          <><span className="animate-spin">⏳</span> Generating PDF…</>
        ) : (
          <><span>↓</span> Download Merit List PDF</>
        )}
      </button>

      <div className="h-4" />
    </Layout>
  );
}
